openapi: 3.0.3
info:
  title: Bookstore API
  description: REST API for managing books, carts, and user authentication.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /api/hello-world:
    get:
      summary: Hello world
      description: Simple endpoint to verify API is running.
      operationId: helloWorld
      tags:
        - auth
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorld"
              example:
                helloWorld: "HELLO_WORLD"

  /api/auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account.
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credentials"
            example:
              username: "john_doe"
              password: "secret123"
      tags:
        - auth
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                username: "john_doe"
        400:
          description: Invalid input
        409:
          description: Username already exists

  /api/auth/login:
    post:
      summary: Authenticate user
      description: Returns a JWT token for authenticated requests.
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credentials"
            example:
              username: "john_doe"
              password: "secret123"
      tags:
        - auth
      responses:
        200:
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
              example:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        401:
          description: Invalid credentials

  /api/books:
    get:
      summary: Retrieve all books
      description: Returns a list of all available books.
      security:
        - bearerAuth: []
      operationId: retrieveAllBooks
      tags:
        - books
      responses:
        200:
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
              example:
                - id: "123"
                  title: "Clean Code"
                  author: "Robert C. Martin"
                  price: 39.99
                - id: "124"
                  title: "Effective Java"
                  author: "Joshua Bloch"
                  price: 45.50
        401:
          description: Unauthorized
    post:
      summary: Add a new book
      description: Creates a new book entry.
      security:
        - bearerAuth: []
      operationId: addBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBookRequest"
            example:
              title: "Domain-Driven Design"
              author: "Eric Evans"
              price: 49.99
      tags:
        - books
      responses:
        201:
          description: Book created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
              example:
                id: "125"
                title: "Domain-Driven Design"
                author: "Eric Evans"
                price: 49.99
        400:
          description: Invalid input
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /api/books/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      summary: Retrieve book details
      description: Returns details of a specific book by ID.
      security:
        - bearerAuth: []
      operationId: retrieveBook
      tags:
        - books
      responses:
        200:
          description: Book details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
              example:
                id: "123"
                title: "Clean Code"
                author: "Robert C. Martin"
                price: 39.99
        401:
          description: Unauthorized
        404:
          description: Book not found
    delete:
      summary: Delete a book
      description: Removes a book by its ID.
      security:
        - bearerAuth: []
      operationId: deleteBook
      tags:
        - books
      responses:
        204:
          description: No Content
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Book not found
    put:
      summary: Update a book
      description: Updates details of a book by ID.
      security:
        - bearerAuth: []
      operationId: updateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBookRequest"
            example:
              title: "Clean Code (Updated)"
              author: "Robert C. Martin"
              price: 42.99
      tags:
        - books
      responses:
        200:
          description: Book updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
              example:
                id: "123"
                title: "Clean Code (Updated)"
                author: "Robert C. Martin"
                price: 42.99
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Book not found

  /api/cart:
    get:
      summary: View cart
      description: Retrieves the cart of the logged-in user.
      security:
        - bearerAuth: []
      operationId: retrieveCart
      tags:
        - cart
      responses:
        200:
          description: Cart details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
              example:
                items:
                  - book:
                      id: "123"
                      title: "Clean Code"
                      author: "Robert C. Martin"
                      price: 39.99
                    quantity: 2
                    totalPrice: 79.98
                totalPrice: 79.98
    post:
      summary: Add item to cart
      description: Adds a book to the user's cart.
      security:
        - bearerAuth: []
      operationId: addCartItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewCartItemRequest"
            example:
              bookId: "123"
              quantity: 2
      tags:
        - cart
      responses:
        201:
          description: Item added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        401:
          description: Unauthorized

  /api/cart/{bookId}:
    parameters:
      - in: path
        name: bookId
        required: true
        schema:
          type: string
    delete:
      summary: Remove item from cart
      description: Removes a book from the user's cart.
      security:
        - bearerAuth: []
      operationId: removeCartItem
      tags:
        - cart
      responses:
        204:
          description: No Content
        400:
          description: Invalid input
        401:
          description: Unauthorized

    put:
      summary: Update item quantity
      description: Updates the quantity of a book in the cart.
      security:
        - bearerAuth: []
      operationId: updateCartItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartItemRequest"
            example:
              quantity: 3
      tags:
        - cart
      responses:
        200:
          description: Cart updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        400:
          description: Invalid input
        401:
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Book:
      type: object
      description: Represents a book in the bookstore.
      required:
        - id
        - title
        - author
        - price
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        price:
          type: number

    UpdateBookRequest:
      type: object
      description: Payload for creating or updating a book.
      required:
        - title
        - author
        - price
      properties:
        title:
          type: string
        author:
          type: string
        price:
          type: number

    Cart:
      type: object
      description: Represents a user's shopping cart.
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        totalPrice:
          type: number

    CartItem:
      type: object
      description: Represents an item in the cart.
      required:
        - book
        - quantity
      properties:
        book:
          $ref: '#/components/schemas/Book'
        quantity:
          type: integer
        totalPrice:
          type: number

    NewCartItemRequest:
      type: object
      description: Payload for adding a new item to the cart.
      required:
        - bookId
        - quantity
      properties:
        bookId:
          type: string
        quantity:
          type: integer
          minimum: 1

    UpdateCartItemRequest:
      type: object
      description: Payload for updating quantity of an item in the cart.
      required:
        - quantity
      properties:
        quantity:
          type: integer
          minimum: 1

    Credentials:
      type: object
      description: User credentials for authentication.
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          format: password

    Token:
      type: object
      description: JWT token for authenticated requests.
      required:
        - token
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    User:
      type: object
      description: Represents a registered user.
      properties:
        username:
          type: string

    HelloWorld:
      type: object
      description: Simple hello world response.
      required:
        - helloWorld
      properties:
        helloWorld:
          type: string
          enum:
            - HELLO_WORLD