openapi: 3.0.3
info:
  title: Bookstore API
  description: REST API for managing books, carts, and user authentication.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /api/hello-world:
    get:
      summary: Hello world
      operationId: helloWorld
      tags:
        - auth
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorld"

  /api/auth/register:
    post:
      summary: Registering the user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credentials"
      tags:
        - auth
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"


  /api/auth/login:
    post:
      summary: Authenticating the current user
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credentials"
      tags:
        - auth
      responses:
        200:
          description: User Authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"

  /api/books:
    get:
      summary: Retrieve all the books
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: retrieveAllBooks
      tags:
        - books
      responses:
        200:
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    post:
      summary: Add new book
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: addBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBookRequest"
      tags:
        - books
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"



  /api/books/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      summary: Retrieve a book details by its id
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: retrieveBook
      tags:
        - books
      responses:
        200:
          description: Book details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Book not found

    delete:
      summary: Deleting a book by its id
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: deleteBook
      tags:
        - books
      responses:
        204:
          description: No Content
        404:
          description: Book not found
    put:
      summary: Update a book by its id
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: updateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBookRequest"
      tags:
        - books
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        404:
          description: Book not found

  /api/cart:
    get:
      summary: View cart of logged-in user
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: retrieveCart
      tags:
        - cart
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    post:
      summary: Add a new item in the cart
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: addCartItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewCartItemRequest"
      tags:
        - cart
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"


  /api/cart/{bookId}:
    parameters:
      - in: path
        name: bookId
        required: true
        schema:
          type: string
    delete:
      summary: Removing a book from the cart
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: removeCartItem
      tags:
        - cart
      responses:
        204:
          description: No Content
    put:
      summary: Update quantity of a book
      security:
        - bearerAuth: [ ]  # <-- Requires JWT token
      operationId: updateCartItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartItemRequest"
      tags:
        - cart
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
        - price
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        price:
          type: number

    UpdateBookRequest:
      type: object
      required:
        - title
        - author
        - price
      properties:
        title:
          type: string
        author:
          type: string
        price:
          type: number

    Cart:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        totalPrice:
          type: number

    CartItem:
      type: object
      required:
        - book
        - quantity
      properties:
        book:
          $ref: '#/components/schemas/Book'
        quantity:
          type: integer
        totalPrice:
          type: number

    NewCartItemRequest:
      type: object
      required:
        - bookId
        - quantity
      properties:
        bookId:
          type: string
        quantity:
          type: integer
          minimum: 1

    UpdateCartItemRequest:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          minimum: 1


    Credentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          format: password

    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: "JWT token for authentication"

    User:
      type: object
      properties:
        username:
          type: string

    HelloWorld:
      type: object
      required:
        - helloWorld
      properties:
        helloWorld:
          type: string
          enum:
            - HELLO_WORLD